name: basic-neural-nets
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - numpy>=1.24.0
  - matplotlib>=3.6.0
  - scikit-learn>=1.2.0
  - tqdm>=4.65.0
  - pip
  - pip:
    - tensorboard>=2.12.0 